name: dr_ai
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ollama_dart: ^0.2.1
  intl: any
  markdown: ^7.3.0
  shared_preferences: ^2.5.1
  encrypt_shared_preferences: ^0.9.8
  flutter_chat_ui: ^1.6.13
  scroll_to_index: ^3.0.1
  uuid: ^4.4.0
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.1
  visibility_detector: ^0.4.0+2
  http: ^1.2.1
  dartx: ^1.2.0
  smooth_page_indicator: ^1.1.0
  transparent_image: ^2.0.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.6
  flutter_markdown: ^0.7.1
  file_picker: ^8.0.3
  file_selector: ^1.0.3
  bitsdojo_window: ^0.1.6
  package_info_plus: ^8.0.0
  version: ^3.0.2
  flutter_displaymode: ^0.6.0
  duration_picker: ^1.2.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  datetime_loop: ^1.2.0
  dynamic_color: ^1.7.0
  volume_controller: ^3.2.0
  universal_html: ^2.2.4
  pwa_install: ^0.0.6
  flutter_chat_types: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo512.png
    - assets/logo512error.png