name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl git unzip xz-utils libglu1-mesa

      # Step 3: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      # Step 4: Cache Flutter build artifacts
      - name: Cache Flutter build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Step 5: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 6: Analyze the project source
      - name: Analyze project source
        run: flutter analyze

      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2

        with:
          flutter-version: 3.27.4
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle


      # Step 7: Run tests
      # - name: Run tests
      #   run: flutter test
