name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable" # Use stable version of Flutter SDK

      # Step 3: Cache Flutter dependencies
      - name: Cache Flutter build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Verify formatting
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # Step 6: Analyze the project source
      - name: Analyze project source
        run: flutter analyze

      # Step 7: Run tests
      - name: Run tests
        run: flutter test
